sudo: false
language: minimal
dist: bionic
before_script:
  - curl -s -L https://github.com/getzola/zola/releases/download/v0.9.0/zola-v0.9.0-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
script:
  - zola build
after_success:
  - git add -f public
  - git commit -m "Deploy"
  - git push -f https://pksunkara:$TOKEN@github.com/pksunkara/pksunkara.github.io `git subtree split --prefix=public`:master > /dev/null 2>&1
branches:
  only:
    - develop
