baseurl: http://pksunkara.com/
languageCode: en
title: pksunkara
googleAnalytics: UA-9209860-4
disqusShortname: pksunkara
params:
  twitter: pksunkara
  github: pksunkara
  facebook: pksunkara
  description: My personal blog
social:
  twitter: pksunkara
  facebook: pksunkara
taxonomies:
  tag: tags
  category: categories
  series: series
metaDataFormat: yaml
disableKinds:
  - section
