name: Deploy
on:
  push:
    branches: [develop]
jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_ONLY: true
      - name: Deploy
        if: ${{ success() }}
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: master
          folder: public
